version: "3"
services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 81:81
            - 82:82
        restart: always
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8080:8080
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 3000:3000
